name: 'Get Repository Metadata'
description: 'Extracts repository name and constructs deployment role name'

outputs:
  repo_name:
    description: 'Repository name (without owner)'
    value: ${{ steps.metadata.outputs.repo_name }}
  repo_owner:
    description: 'Repository owner'
    value: ${{ steps.metadata.outputs.repo_owner }}
  deployment_role_name:
    description: 'Constructed deployment role name (github-actions-{owner}-{repo})'
    value: ${{ steps.metadata.outputs.deployment_role_name }}

runs:
  using: 'composite'
  steps:
    - name: Extract repository metadata
      id: metadata
      shell: bash
      run: |
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        REPO_OWNER="${{ github.repository_owner }}"
        DEPLOYMENT_ROLE_NAME="github-actions-${REPO_OWNER}-${REPO_NAME}"

        echo "repo_name=${REPO_NAME}" >> $GITHUB_OUTPUT
        echo "repo_owner=${REPO_OWNER}" >> $GITHUB_OUTPUT
        echo "deployment_role_name=${DEPLOYMENT_ROLE_NAME}" >> $GITHUB_OUTPUT

        echo "Repository: ${REPO_OWNER}/${REPO_NAME}"
        echo "Deployment role name: ${DEPLOYMENT_ROLE_NAME}"
