name: 'Deploy CloudFormation Stack'
description: 'Validates and deploys a CloudFormation template with optional parameters'

inputs:
  # required parameters
  stack_name:
    description: 'CloudFormation stack name'
    required: true

  template_file:
    description: 'Path to CloudFormation template file'
    required: true

  deployment_role_arn:
    description: 'ARN of the deployment role to assume for CloudFormation operations. If not provided, defaults to github-actions-{owner}-{repo} or uses DEPLOYMENT_ROLE_NAME input.'
    required: false
    default: ''

  deployment_role_name:
    description: 'Override deployment role name (without account/ARN prefix). Defaults to github-actions-{owner}-{repo}. Use this for special roles like github-actions-create-deployment-role.'
    required: false
    default: ''

  # parameters with defaults
  aws_region:
    description: 'AWS region for deployment'
    required: false
    default: 'eu-west-2'

  oidc_entry_role_arn:
    description: 'ARN of the OIDC entry role (github-actions-oidc-entry-role)'
    required: false
    default: arn:aws:iam::020844256789:role/github-actions-oidc-entry-role

  parameters:
    description: 'CloudFormation parameters (space-separated KEY=VALUE pairs)'
    required: false
    default: ''

  capabilities:
    description: 'CloudFormation capabilities (e.g., CAPABILITY_NAMED_IAM)'
    required: false
    default: 'CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND'

  # Descriptive Optional Parameters
  summary_title:
    description: 'Title for deployment summary'
    required: false
    default: 'Deployment Summary'

  summary_icon:
    description: 'Icon emoji for deployment summary'
    required: false
    default: ':rocket:'

outputs:
  stack_outputs:
    description: 'JSON string of stack outputs'
    value: ${{ steps.get-outputs.outputs.stack_outputs }}

runs:
  using: 'composite'
  steps:
    - name: Construct deployment role ARN
      id: deployment-role
      shell: bash
      run: |
        # Hardcoded AWS account number
        ACCOUNT_ID="020844256789"

        # Determine deployment role ARN
        if [ -n "${{ inputs.deployment_role_arn }}" ]; then
          # Use provided ARN
          DEPLOYMENT_ROLE_ARN="${{ inputs.deployment_role_arn }}"
          echo "Using provided deployment role ARN: ${DEPLOYMENT_ROLE_ARN}"
        elif [ -n "${{ inputs.deployment_role_name }}" ]; then
          # Use provided role name
          DEPLOYMENT_ROLE_ARN="arn:aws:iam::${ACCOUNT_ID}:role/${{ inputs.deployment_role_name }}"
          echo "Using provided role name: ${{ inputs.deployment_role_name }}"
          echo "Constructed ARN: ${DEPLOYMENT_ROLE_ARN}"
        else
          # Default: construct from repository metadata
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          REPO_OWNER="${{ github.repository_owner }}"
          ROLE_NAME="github-actions-${REPO_OWNER}-${REPO_NAME}"
          DEPLOYMENT_ROLE_ARN="arn:aws:iam::${ACCOUNT_ID}:role/${ROLE_NAME}"
          echo "Using default role name: ${ROLE_NAME}"
          echo "Constructed ARN: ${DEPLOYMENT_ROLE_ARN}"
        fi

        echo "deployment_role_arn=${DEPLOYMENT_ROLE_ARN}" >> $GITHUB_OUTPUT

    - name: Configure AWS credentials (OIDC Entry Role)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.oidc_entry_role_arn }}
        aws-region: ${{ inputs.aws_region }}
        role-session-name: ${{ github.repository_owner }}-${{ github.event.repository.name }}

    - name: Configure AWS credentials (Deployment Role)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ steps.deployment-role.outputs.deployment_role_arn }}
        aws-region: ${{ inputs.aws_region }}
        role-session-name: ${{ github.repository_owner }}-${{ github.event.repository.name }}-deploy
        role-chaining: true

    - name: Validate CloudFormation template
      shell: bash
      run: |
        echo "Validating CloudFormation template: ${{ inputs.template_file }}"
        aws cloudformation validate-template \
          --template-body file://${{ inputs.template_file }}

    - name: Deploy CloudFormation stack
      shell: bash
      run: |
        echo "Deploying CloudFormation stack: ${{ inputs.stack_name }}"

        # Deploy!
        aws cloudformation deploy \
          --stack-name ${{ inputs.stack_name }} \
          --template-file ${{ inputs.template_file }} \
          --tags \
            Project=${{ github.repository_owner }}-${{ github.event.repository.name }} \
            ManagedBy=GitHubActions \
            GitCommit=${{ github.sha }} \
          --no-fail-on-empty-changeset \
          --region ${{ inputs.aws_region }} \
          --parameter-overrides ${{ inputs.parameters }} \
          --capabilities ${{ inputs.capabilities }}

    - name: Get stack outputs
      id: get-outputs
      shell: bash
      run: |
        echo "Fetching stack outputs..."
        OUTPUTS=$(aws cloudformation describe-stacks \
          --stack-name ${{ inputs.stack_name }} \
          --query 'Stacks[0].Outputs' \
          --output json)

        echo "Stack outputs:"
        echo "$OUTPUTS" | jq -r '.[] | "\(.OutputKey): \(.OutputValue)"'

        # Export outputs as JSON for potential use by caller
        echo "stack_outputs<<EOF" >> $GITHUB_OUTPUT
        echo "$OUTPUTS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Display deployment summary
      shell: bash
      run: |
        echo "### ${{ inputs.summary_title }} ${{ inputs.summary_icon }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Stack Name:** ${{ inputs.stack_name }}" >> $GITHUB_STEP_SUMMARY
        echo "**Template:** ${{ inputs.template_file }}" >> $GITHUB_STEP_SUMMARY
        echo "**Region:** ${{ inputs.aws_region }}" >> $GITHUB_STEP_SUMMARY
        echo "**Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

        # Display stack outputs if they exist
        OUTPUTS=$(aws cloudformation describe-stacks \
          --stack-name ${{ inputs.stack_name }} \
          --query 'Stacks[0].Outputs' \
          --output json 2>/dev/null || echo "[]")

        if [ "$(echo "$OUTPUTS" | jq 'length')" -gt 0 ]; then
          echo "#### Stack Outputs" >> $GITHUB_STEP_SUMMARY
          echo "$OUTPUTS" | jq -r '.[] | "- **\(.OutputKey):** \(.OutputValue)"' >> $GITHUB_STEP_SUMMARY
        fi
