name: 'Python Quality Check'
description: 'Run Python linting or testing with uv and caching'

inputs:
  python-version:
    description: 'Python version to use (e.g., 3.13, 3.14)'
    required: true

  check-type:
    description: 'Type of check to run: "lint" or "test"'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python ${{ inputs.python-version }}
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: uv sync --group development

    # lint checks
    - name: Run ruff check
      if: inputs.check-type == 'lint'
      shell: bash
      run: uv run ruff check speedtest/ tests/

    - name: Run ruff format check
      if: inputs.check-type == 'lint'
      shell: bash
      run: uv run ruff format --check speedtest/ tests/

    - name: Run pyrefly typechecking
      if: inputs.check-type == 'lint'
      shell: bash
      run: uv run pyrefly check speedtest/ tests/

    # test checks
    - name: Run tests
      if: inputs.check-type == 'test'
      shell: bash
      run: uv run pytest -v
