name: 'Deploy Deployment Role (Conditional)'
description: 'Conditionally deploy the deployment role CloudFormation stack'

inputs:
  run-deploy-deployment-role:
    description: 'Whether to run the deployment'
    required: true

  universe:
    description: 'Deployment universe (e.g., production)'
    required: true

  deployment-role-arn:
    description: 'ARN of the role to assume for deployment'
    required: true

  deployment-role-stack-name:
    description: 'CloudFormation stack name for deployment role'
    required: true

  service-name:
    description: 'Service name for parameters'
    required: true

  deployment-iam-role-name:
    description: 'IAM role name for deployment'
    required: true

  aws-region:
    description: 'AWS region for deployment'
    required: false
    default: 'eu-west-2'

runs:
  using: 'composite'
  steps:
    - name: Skip deployment
      if: inputs.run-deploy-deployment-role != 'true'
      shell: bash
      run: echo "Skipping deployment role deployment (run-deploy-deployment-role=${{ inputs.run-deploy-deployment-role }})"

    - name: Checkout code
      if: inputs.run-deploy-deployment-role == 'true'
      uses: actions/checkout@v4

    - name: Deploy deployment role CloudFormation stack
      if: inputs.run-deploy-deployment-role == 'true'
      uses: ./.github/actions/deploy-cloudformation
      with:
        deployment-role-arn: ${{ inputs.deployment-role-arn }}
        stack-name: ${{ inputs.universe }}-${{ inputs.deployment-role-stack-name }}
        template-file: infrastructure/deployment-role.yml
        parameters: Universe=${{ inputs.universe }} ServiceName=${{ inputs.service-name }} DeploymentRoleName=${{ inputs.deployment-iam-role-name }}
        summary-title: Deployment Role Created (${{ inputs.universe }})
        aws-region: ${{ inputs.aws-region }}
