name: 'Validate CloudFormation Templates'
description: 'Validate CloudFormation templates using cfn-lint and AWS validate-template'

inputs:
  template-paths:
    description: 'Space-separated list of CloudFormation template paths to validate'
    required: true

  aws-region:
    description: 'AWS region for validation'
    required: false
    default: 'eu-west-2'

  oidc-entry-role-arn:
    description: 'ARN of the OIDC entry role (github-actions-oidc-entry-role)'
    required: false
    default: 'arn:aws:iam::020844256789:role/github-actions-oidc-entry-role'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Set up Python
      shell: bash
      run: uv python install 3.13

    - name: Install dependencies
      shell: bash
      run: uv sync --group development

    - name: Static validation with cfn-lint
      shell: bash
      run: |
        echo "=== Static Validation with cfn-lint ==="
        TEMPLATES="${{ inputs.template-paths }}"
        VALIDATION_FAILED=0

        for template in $TEMPLATES; do
          echo ""
          echo "Linting: $template"

          if [ ! -f "$template" ]; then
            echo "❌ Error: Template file not found: $template"
            VALIDATION_FAILED=1
            continue
          fi

          if cfn-lint "$template"; then
            echo "✅ cfn-lint passed: $template"
          else
            echo "❌ cfn-lint failed: $template"
            VALIDATION_FAILED=1
          fi
        done

        if [ $VALIDATION_FAILED -eq 1 ]; then
          echo ""
          echo "❌ cfn-lint validation failed"
          exit 1
        fi

        echo ""
        echo "✅ All templates passed cfn-lint"

    - name: Configure AWS credentials (OIDC Entry Role)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.oidc-entry-role-arn }}
        aws-region: ${{ inputs.aws-region }}
        role-session-name: ${{ github.repository_owner }}-${{ github.event.repository.name }}-validate

    - name: AWS CloudFormation validation
      shell: bash
      run: |
        echo ""
        echo "=== AWS CloudFormation Validation ==="
        TEMPLATES="${{ inputs.template-paths }}"
        VALIDATION_FAILED=0

        for template in $TEMPLATES; do
          echo ""
          echo "Validating with AWS: $template"

          if aws cloudformation validate-template --template-body file://"$template" > /dev/null 2>&1; then
            echo "✅ AWS validation passed: $template"
          else
            echo "❌ AWS validation failed: $template"
            aws cloudformation validate-template --template-body file://"$template" || true
            VALIDATION_FAILED=1
          fi
        done

        if [ $VALIDATION_FAILED -eq 1 ]; then
          echo ""
          echo "❌ AWS CloudFormation validation failed"
          exit 1
        fi

        echo ""
        echo "✅ All templates passed AWS validation"
